"""empty message

Revision ID: 531c19a73f7c
Revises: ba3345bd8885
Create Date: 2020-05-06 00:33:09.436718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531c19a73f7c'
down_revision = 'ba3345bd8885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_lists')
    # ### end Alembic commands ###
